### ISSUE TITLE
Nuvolaris First Step: nuv debug config didn't return "postgres_url"

### ISSUE THREAD

**Issue by diegoconti77** [nuvolaris/nuvolaris-bugs#13]
Inside the Nuvolaris First Steps it is mentioned to run the command "nuv debug config" to ge tthe postgres_url but the command didn't show the mentioned information.

For example, to get the postgres_url you can execute "nuv debug status".

**Comment by ghost** [comment]
@diegoconti77 that part of the documentation it is still under heavy refactoring and it is not completely reliable

You should use `nuv debug status` that should return something similar to

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    apihost: http://localhost:3233
    controller_version: ghcr.io/nuvolaris/openwhisk-controller:0.3.0-morpheus.22122609
    couchdb-init_version: ghcr.io/nuvolaris/nuvolaris-operator:0.3.0-dev.2308142149
    couchdb_version: apache/couchdb:2.3
    postgres_database: nuvolaris
    postgres_host: nuvolaris-postgres.nuvolaris.svc.cluster.local
    postgres_password: xxxxxxxxxx
    postgres_port: "5432"
    postgres_url: postgresql://nuvolaris:Lt47VX5iVcbd@nuvolaris-postgres.nuvolaris.svc.cluster.local:5432/nuvolaris
    postgres_username: nuvolaris
  creationTimestamp: "2023-09-10T09:54:49Z"
  name: config
  namespace: nuvolaris
  resourceVersion: "1147"
  uid: 627b9370-d7d6-43e8-afde-6944179761fe
```

Actually the command `nuv debug config` shows the operator deployed configuration. 

Thanks for pointing it out, we will fix this part in the documentation asap.
