### ISSUE TITLE
PersistentVolumeClaim issue during setup in MicroK8s

### ISSUE THREAD

**Issue by aleroxx** [nuvolaris/nuvolaris-bugs#15]
I'm using MicroK8s inside an Ubuntu VM (both installed by me, with a private IP address and a local DNS) and I'm trying to install Nuvolaris.

After installing it and running "nuv -update", these are the commands that I've executed.
Note: I'm trying to setup the base system to check if it works in my environment.

Setup hung due to a timeout while starting the couchdb-0 pod.
I did some investigating and found there was an issue with a PersistentVolumeClaim that is still pending: I don't know if that's the cause of the problem.

You can find in attach the executed commands with their results.

I hope this information is enough to analyze and resolve the issue.
Thanks!
[error.txt](https://github.com/nuvolaris/nuvolaris-bugs/files/12570630/error.txt)

**Comment by msciabarra** [comment]
Actually we do not support (yet) installation in microk8s from the inside of a vm with a self-installed microk8s. The procedure implemented in `nuv` is to let install microk8s from the outside, accessing with ssh to the server.
It you really want to do this, first install microk8s using this script:
https://github.com/nuvolaris/olaris/blob/0.3.0/cloud/mk8s/mk8s.sh
then export the kubeconfig with `microk8s config >~/.kube/config` and finally install with 
`nuv setup cluster`
