### ISSUE TITLE
Tutorial Documentation Notes

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris-bugs#20]
Gathering of all the notees on the tutorial

**Comment by msciabarra** [comment]
Please do not stick to installing the devcluster, instead refer to installation documentation, and suggest to enable the services with `nuv update apply` instead of just install the devcluster from scratch

**Comment by mdigirolamo-nuv** [comment]
In general is better use a cloud so we don't have [http://localhost:80](http://localhost:80http//url) but ok: whisk API host set to http://4.236.203.129.nip.io for example

**Comment by msciabarra** [comment]
some people cannot easily find documentation for specific cloud so make it more evident

**Comment by msciabarra** [comment]
when you set the action "send-email" you use a bash specific idiom (FROM=<...>) that if you are using powershell is configuring. Better to write directly `-p FROM <your email>` in the example command.

**Comment by msciabarra** [comment]
add some notes for reading the logs with `nuv activation logs` and `nuv activation poll`

**Comment by msciabarra** [comment]
provide some hints for debugging the sendemail checking if the email was sent in sendgrid and read what happened in th logs

**Comment by mdigirolamo-nuv** [comment]
I used the command 
 kubectl -n nuvolaris exec -ti po/nuvolaris-postgres-1-0 -- psql  postgresql://nuvolaris:PtyEBKbwJIiE@nuvolaris-postgres.nuvolaris.svc.cluster.local:5432/nuvolaris
and I found that the table contacts was created but was empty.
I put manually this 
INSERT INTO contacts (id,name,email,phone,message) VALUES (gen_random_uuid(),'Mirella Di Girolamo','mirella@sciabarra.com','12369874111','Saluti');
and it worked.
The code in the tutorial doesn't work.
It must be fixed

**Comment by mdigirolamo-nuv** [comment]
solved the problem with psdb by modifying create-table.js like this CREATE TABLE IF NOT EXISTS contacts_nv (
        contacts_id serial PRIMARY KEY,... That is, I use the serial instead of the UUID

**Comment by msciabarra** [comment]
tutorial should include also a reference to using /api/my to invoke the form

**Comment by mdigirolamo-nuv** [comment]
If the url does not exist, a request to enter username and password will appear, this is a feature of open whisk. It might be nice to report this feature.

**Comment by mdigirolamo-nuv** [comment]
console.log("Status from SendGrid request: " + res.status); doesn't work it must be console.log("Status from SendGrid request: " + response.status);

**Comment by giusdp** [comment]
I'm closing this in favor of https://github.com/nuvolaris/nuvolaris/issues/315
