### ISSUE TITLE
nuv: Unable to configure & provision Azure AKS

### ISSUE THREAD

**Issue by eduFlowers** [nuvolaris/nuvolaris-bugs#30]
**nuv version:** `3.0.1-beta.2310201736`

Following instructions to install nuvolaris, in particular the prerequisites section to [configure and provision an azure AKS cluster](https://nuvolaris.github.io/nuvolaris/3.0.0/installation/prereq-aks.html), after executing the command:
`nuv cloud aks create`

I get the following error:
**_ERROR: the following arguments are required: --location/-l_**

Hereafter a screenshot of the result of the command
`nuv config aks`
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/f99a8908-9f78-4ad2-95ef-8c92e622b487)

This instead the one for the command
`nuv cloud aks create`
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/fe29e5ca-d939-4de5-8919-eff98d6c0e8b)

I've tried both leaving defaults (as suggested in the documentation) and setting different values but got same error.

**Comment by msciabarra** [comment]
what is the value of the configured AKS "region"?
you can see this with `nuv -config AKS_REGION`
did you configure with `nuv config aks`?

**Comment by eduFlowers** [comment]
Yes. I used
`nuv config aks`

here the full log of it
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/7ba20b1b-4f3f-4a71-8c4f-7593e0336fe4)

The last location I've tried was **AKS_REGION=westeurope** but also tried the default one suggested in the doc **eastus** but got same error.

**Comment by msciabarra** [comment]
please edit line 63 of ~/.nuv/3.0.0/olaris/cloud/aks/nuvfile.yml and put "silent: false"
then report the output.
this is the relevant code
https://github.com/nuvolaris/olaris/blob/b3d4aa04c12d8c81ed301c5a390896f327a4f9f8/cloud/aks/nuvfile.yml#L63
It should create the resource group in the $AKS_REGION, this will show the actual command executed.
Also, try remove the resource group left over with `nuv cloud aks delete`

**Comment by eduFlowers** [comment]
This is the output of `nuv cloud aks create` after updating silent: false of nuvfile.yml
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/2659913e-45fa-4b19-be94-965a832de46f)

This instead the output of `nuv cloud aks delete`
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/116c3184-7d54-4d2c-b49a-aa29295a3d5d)

Seems that each value was saved twice when executing `nuv config aks`
for example when asked for AKS Name for Cluster I've specified nuvolaris but them seems that it was saved as **nuvolaris nuvolaris** (see error on delete command) and same for others.

The strange thing is that the final output seems to be ok instead (see image below)
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/91bbf9c2-a49f-4e95-bee4-a7263ac238e6)

### *** UPDATE ***

I confirm that values are saved twice. I've added an echo to see values for name & region and this is the result:
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/ad38791e-ec73-4948-97c7-9a66fda31eba)

**Comment by msciabarra** [comment]
Oh well... looks a problem in the input then!
`nuv config reset` and start again with the configuration.
Check the actual value with `nuv -config -d | grep AKS`

**Comment by eduFlowers** [comment]
Yes. It's a input problem.
Just tried again after reset.

First run with defaults (except for AKS_REGION that is custom)
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/aeb6aef2-816d-4b68-8b8e-ea1b5eb9a30a)

Values are empty (except for the custom value)
Executing then create command, now it fails on **name**

Second run with all custom values
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/187ebdd4-8ee6-4d28-a712-4c01da85de46)

Values seems correct but when executing the create command they have input value concatenated (nuvolaris nuvolaris, westeurope westeurope, etc).
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/ea1d1557-b621-4608-ab73-a0bc68247c00)

**Comment by msciabarra** [comment]
I guess you are using windows... that is the platform on one of us actually uses...
There is a workaround to actually read the input. Is it possible you used something different from powershell to provide input?
We will investigate on this, however as a workaround I suggest you set the values with
nuv -config KEY=VALUE:
  nuv -config AKS_REGION=westeurope 
ando so on...

**Comment by eduFlowers** [comment]
Yes, I'm using windows 11 with Git Bash (that I use during development 😄)
With the suggestion you provided (set values directly using `nuv -config KEY=VALUE`) I was able to go ahead with the process but now it gives me an error related to the ssh key (generated using **ssh-keygen**)
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/57302876/3bd5c8dc-3b07-4837-926b-f0b8399a4e53)

**Comment by cor277** [comment]
Hi @eduFlowers , I created and destroyed an aks in my tenant 2 or 3 times in last month, whitout any problem. I can try to check with you and support trying redo your steps in my MS tenant. So, 
first question: az tool is the last update?

**Comment by cor277** [comment]
I see that you use git bash, in my installation I used only powershell.
Can you try whitout git bash?

**Comment by msciabarra** [comment]
the error about invalid ssh-keygen is unrelated to nuv and there is a suggestion how to fix it. Closing as supporting non standard shells  and misconfigurations in windows is not in scope.

**Comment by eduFlowers** [comment]
@msciabarra, @cor277  all issues above were related to the use of Git Bash. Now I used PowerShell and I was able to create the aks cluster in azure!

Anyways the use of a particular shell is not indicated in the documentation (at least I didn't see it).
