### ISSUE TITLE
Error during setup server on Ubuntu Server

### ISSUE THREAD

**Issue by fcolasante** [nuvolaris/nuvolaris-bugs#32]
Hi,
I am attempting to set up a Nuvolaris cluster by following the guide with this command:

```
nuv setup server 192.168.2.33 itoperation
```

### My Setup
- Ubuntu Server 22.04.4 LTS with SSH-key access requiring a passphrase, and passwordless sudo. The VM is deployed on HyperV with a static IP.
- Nuv CLI installed on a Windows 10 client.

### Error

```
....
NAME           READY   STATUS    RESTARTS   AGE
controller-0   1/1     Running   0          6m2s
0 waiting for pod/controller-0 to be ready
pod/controller-0 condition met
http://79.47.198.XXX.nip.io
export KUBECONFIG=C:\Users\francesco\.nuv\tmp\kubeconfig
export http://79.47.198.XXX.nip.io
export 82ebc008-c12a-4583-a2f4-f0d90a260b0f:WtCkPjGuz8OazFHZoWuLOvwquujuKSY9m018FXZ6amM1D1Im17vSCJj16lKsiuf5
Unable to obtain the list of available namespaces: Get "http://79.47.198.XXX.nip.io/api/v1/namespaces": dial tcp 79.47.198.XXX:80: connectex: No connection could be made because the target machine actively refused it.
Unable to obtain the list of available namespaces: Get "http://79.47.198.XXX.nip.io/api/v1/namespaces": dial tcp 79.47.198.XXX:80: connectex: No connection could be made because the target machine actively refused it.
....
```

It attempts to access my Kubernetes cluster via my public IP 79.47.198.XXX instead of the private IP 192.168.2.33. I noted in the guide that it can also be deployed in intranet environments.

**Comment by msciabarra** [comment]
You have an internal server and you did not set the apihost so as a result it is trying to autodetect the ip but since it is going through your nat you got the public ip of your router! The documentation states it should be a publicly accessible server. In any case you can just sove with `nuv config apihost 192.168.2.33` so nuv will use the internal ip instead of the autodectected one.

**Comment by fcolasante** [comment]
Thank you Michele, it works!
However, I did not find in the documentation the prerequisites of "publicly accessible server". So, I suggest to update the following page [prereq-server.html)](https://nuvolaris.github.io/nuvolaris/3.1.0/installation/prereq-server.html).
