### ISSUE TITLE
Tutorial step `nuv upload web/` not producing the expected result

### ISSUE THREAD

**Issue by ggorge-me** [nuvolaris/nuvolaris-bugs#33]
I'm following this tutorial https://nuvolaris.github.io/nuvolaris/3.0.0/tutorial/first-steps.html with my a local development cluster.

1. `nuv setup devcluster`
2. `nuv config enable --postgres --static --minio --cron`
3. `nuv update apply` -> Welcome to Nuvolaris static content distributor landing page!!!  is displayed on http://localhost
4. `nuv web upload web/ --verbose` -> Uploading index.html...

But I'm not able to see the updated web page.

**Comment by sciabarracom** [comment]
checking

**Comment by ggorge-me** [comment]
@sciabarracom thank you. I'm also trying to debug the thing by myself: If I understood well (I'm not a k8s expert) the static content is served by an nginx pod doing reverse proxy for minio.

After exposing minio console (`kubectl port-forward pod/minio-deployment-7f55d44b8d-7dhqf 9090:9090 -n nuvolaris`) I can see that the index.html is not getting updated by `nuv web upload web/` command.

I noticed that if I upload a new file to minio via web console I can see it in the browser (eg: `http://localhost/index2.html`).

**Comment by sciabarracom** [comment]
it is exposed by minio

**Comment by sciabarracom** [comment]
and you need to login and get the secrets

**Comment by ggorge-me** [comment]
@sciabarracom yes, I'm logged in the minio console with `nuvolaris` user and the `SECRET_MINIO_NUVOLARIS` as password.

I can see the `index.html` original file. And I can add a new file using the web console. The new file added is then displayed in the browser.

Minio seems working:

![image](https://github.com/user-attachments/assets/7f922418-4e0e-455b-86e6-b04ed25d2908)

**Comment by ghost** [comment]
@ggorge-etiqa I suspect that the nuv web upload command is not reading properly the required credentials. And this would probably requires an update on the nuv command related tasks. Please let me check if that's the case and I will come back to you asap.

**Comment by sciabarracom** [comment]
A couple of comments:
1. we are working  since a few months on [OpenServerless](https://openserverless-demo.netlify.app) so probably you have better luck using openserverles and the ops tool and the updated documentation
2. to get the latest tasks use export NUV_BRANCH=3.0.0-testing and the run `nuv -update` (we are publing the test branch now on the main)
3. the port to use is https://localhost:80
4. check you have the secrets for minio: `nuv -config -d | grep 'MINIO'` as they are required - those are obtained with nuv -login http://localhost:3233 nuvolaris
5. You can get the password for the nuvolaris user issuing the command kubectl -n nuvolaris get wsk/controller -ojsonpath='{.spec.nuvolaris.password}'

**Comment by ghost** [comment]
@ggorge-etiqa we've uploaded an updated version of nuv tasks to the default branch, that you can enforce by unsetting export NUV_BRANCH=3.0.0-testing, or explicitly setting export NUV_BRANCH=3.0.0.

I suggest to retry a fresh install using something like

1. nuv -update
2. nuv setup cluster --uninstall
3. nuv config reset
4. nuv config enable --postgres --static --minio --cron
5. nuv setup devcluster
6.  nuv -login http://localhost:80/ nuvolaris
7. nuv web upload web/ --verbose -> Uploading index.html...

You can get the password for the nuvolaris user issuing the command `kubectl -n nuvolaris get wsk/controller -ojsonpath='{.spec.nuvolaris.password}'`

**Comment by ggorge-me** [comment]
Thanks @francescotimperi now it works :-)

I think that step number 6 `nuv -login http://localhost:80/ nuvolaris` is not really clear (probably missing) in the tutorial.

**Comment by ghost** [comment]
@ggorge-etiqa indeed you are right, login part is missing in the tutorial, but actually I will try to include the login as part of the setup process. Current setup process perform a partial login, setting up only the part to configure the Openwhisk client part, but does not perform a full login as nuv -login command does.

I will provide an updated setup process asap. Didn't had the time to include this patch yesterday.
