### ISSUE TITLE
Installing on gcloud

### ISSUE THREAD

**Issue by afrasccella** [nuvolaris/nuvolaris-bugs#4]
launcing nuv config gke, nuv don't set all parameters leaving defualt when it is possible

 
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/65504443/41b33b40-4ffe-434a-8838-96bc4b94bc3e)

So if i try to go on on with nuv cloud gke create i receive an error

![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/65504443/0ed55abc-f0cf-4735-a6ef-4eb4129bd679)

Ambiente (windows 10, prompt dos)

**Comment by msciabarra** [comment]
Fixed - use nuv -update to get the new tasks
