### ISSUE TITLE
Document fixes collector

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris-bugs#6]
Collector of all the documentation related notes.

**Comment by msciabarra** [comment]
Document you need to enable the following permissions for Google Cloud

```
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable dns.googleapis.com
gcloud services enable iamcredentials.googleapis.com
gcloud services enable iam.googleapis.com
gcloud services enable servicemanagement.googleapis.com
gcloud services enable serviceusage.googleapis.com
gcloud services enable storage-api.googleapis.com
gcloud services enable storage-component.googleapis.com
gcloud services enable deploymentmanager.googleapis.com
gcloud services enable resourcemanager.projects.delete
```

**Comment by msciabarra** [comment]
In the quick start there is a long discussion before explaining the command to install the cluster is `nuv setup cluster` it should be put first, and then the notes

**Comment by mdigirolamo-nuv** [comment]
In the quick start is better to explain in this way:
1. scarica e installa questo prima di tutto
https://awscli.amazonaws.com/AWSCLIV2.msi

2. addess installa Nuvolaris da qui da qui
[bit.ly/nuv3](http://bit.ly/nuv3)

3. Apri il terminale: 
premi <windows>+R e scrivi powershell
e controlla che c'è nuv scrivendo

  nuv -info

4. Adesso configura il cluster

   nuv config eks

e rispondi ai primi 3 (chiave/password/regione)

   AAA

   ZZZ

   eu-central-1

tutti gli altri premi invio

4. installa

Prima connettiti al cluster

    nuv cloud eks kubeconfig

e poi installa

   nuv setup cluster

**Comment by msciabarra** [comment]
some people cannot easily find documentation for specific cloud so make it more evident

**Comment by msciabarra** [comment]
there are missing links related to install the ssh keys

**Comment by msciabarra** [comment]
Document permission to be able to create a gke cluster

gcloud projects add-iam-policy-binding [PROJECT_ID] --member="user:[USER_EMAIL]" --role="roles/container.clusterAdmin"
gcloud projects add-iam-policy-binding [PROJECT_ID] --member="user:[USER_EMAIL]" --role="roles/container.admin"
gcloud projects add-iam-policy-binding [PROJECT_ID] --member="user:[USER_EMAIL]" --role="roles/iam.serviceAccountUser"

**Comment by msciabarra** [comment]
document there are now a package for older versions of glibc (debian 11, ubuntu 20, redhat 8)

**Comment by AntonioPiga** [comment]
If a user wants to uninstall nuv from his local machine? Can you give him some commands/tutorial?

**Comment by msciabarra** [comment]
there are we should add in the tutorial

**Comment by msciabarra** [comment]
In the tutorial there are references to the `nuv debug` that are available ONLY for people who installed it and they have the kubeconfig availabe - remove them and instructs to use the secrets instead with `nuv -config -d` and ${SECRET_NAME} in the manifest

**Comment by zeph** [comment]
- https://nuvolaris.github.io/nuvolaris/3.0.0/tutorial/first-steps.html#_the_contact_package

menziona questo altro pacchetto... ma non c'e' nella mia installazione...
`/nuvolaris/hello    private     <-- a default package created during deployment`

l'enpoint della action e' https://nuvolaris.app/api/v1/web/serra/contact/submit
non quello suggerito nell'how-to... $ <apihost>/api/v1/web/nuvolaris/contact/submit


output of this command is way different from the example in 
- https://nuvolaris.github.io/nuvolaris/3.0.0/tutorial/form-validation.html

```
% nuv action get contact/submit
ok: got action contact/submit
{
    "namespace": "serra/contact",
    "name": "submit",
    "version": "0.0.1",
    "exec": {
        "kind": "nodejs:18",
        "binary": false
    },
    "annotations": [
        {
            "key": "web-export",
            "value": true
        },
        {
            "key": "raw-http",
            "value": false
        },
        {
            "key": "final",
            "value": true
        },
        {
            "key": "provide-api-key",
            "value": false
        },
        {
            "key": "exec",
            "value": "nodejs:18"
        }
    ],
    "parameters": [
        {
            "key": "dbUri",
            "value": "postgresql://serra:XXXXX@nuvolaris-postgres.nuvolaris.svc.cluster.local:5432/serra"
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10,
        "concurrency": 1
    },
    "publish": false,
    "updated": 1700154827984
}
```

again, action not in line with what's being reported by the example...
- https://nuvolaris.github.io/nuvolaris/3.0.0/tutorial/use-database.html#_trying_the_sequence

```
% nuv url contact/submit-write
https://nuvolaris.app/api/v1/web/serra/contact/submit-write
```
instead of 
```
nuv url contact/submit-write
<apihost>/api/v1/web/nuvolaris/contact/submit-write
```

ok, failing the submit with 
```
{
  "code": "WhGIZNTiL7Y5D37rx5LUrUQnfz3kuyzP",
  "error": "There was an error processing your request."
}
```

found... there is a typo in the write.js at

```
    return {
        body: args.body,
        name,
        email,
        phone,
        message
     };
```

`args.body` needs a comma in the end

[...]

`nuv devel scan` does not write the manifest.yaml on the filesystem

**Comment by msciabarra** [comment]
document
```
export PREFL_NO_CPU_CHECK=1
export PREFL_NO_MEM_CHECK=1
```
to disable cpu and memory check

**Comment by AntonioPiga** [comment]
released today new version with fixes included
